name: C/C++ CI

on: [push]

jobs:
  build run and upload:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: gcc -o printh src/printh.c src/nifti1_io.c src/znzlib.c -lm
    - name: run it
      run: ./printh
    - uses: actions/upload-artifact@v1
      with:
        name: printh
        path: printh
      
